apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: leave-management
type: Opaque
stringData:
  JWT_SECRET: change_this_to_a_long_random_secret
  SOCKET_SERVICE_TOKEN: change_this_to_a_private_service_token
