apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: leave-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: auth-service
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: mongo:latest
          command:
            - sh
            - -c
          args:
            - until mongosh "$MONGO_URI" --eval "db.adminCommand('ping')" >/dev/null 2>&1; do sleep 2; done
          envFrom:
            - configMapRef:
                name: app-configmap
      containers:
        - name: auth-service
          image: lms-auth-service:ci
          imagePullPolicy: Never
          ports:
            - containerPort: 1001
          envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: leave-management
spec:
  selector:
    app: auth-service
  ports:
    - port: 1001
      targetPort: 1001
