apiVersion: batch/v1
kind: Job
metadata:
  name: management-migration
  namespace: leave-management
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: postgres:15-alpine
          command:
            - sh
            - -c
          args:
            - until pg_isready -h postgres -p 5432 -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do sleep 2; done
          envFrom:
            - configMapRef:
                name: app-configmap
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
      containers:
        - name: management-migration
          image: lms-management-service:ci
          imagePullPolicy: Never
          command:
            - sh
            - -c
          args:
            - npx sequelize-cli db:migrate
          envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secret
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
